spring:
    application:
        name: game-tracker-api
    datasource:
        url: jdbc:postgresql://localhost:5432/gametrackerapi
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true